//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDeviceManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public Connection()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int ID { get; set; }
        public int ConnectionTypeID { get; set; }
        public Nullable<int> BaudRate { get; set; }
        public Nullable<int> DataBits { get; set; }
        public Nullable<int> StopBits { get; set; }
        public Nullable<int> RTSCTS { get; set; }
        public Nullable<int> DTR { get; set; }
        public Nullable<int> RTS { get; set; }
        public Nullable<int> XonXoff { get; set; }
    
        public virtual ICollection<Device> Devices { get; set; }
        public virtual ConnectionType ConnectionType { get; set; }
    }
}
