//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDeviceManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.Nodes = new HashSet<Node>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int DeviceTypeID { get; set; }
        public Nullable<int> ConnectionID { get; set; }
        public string Description { get; set; }
        public string SerialNumber { get; set; }
        public string FirmwareRevision { get; set; }
        public string PartNumber { get; set; }
        public string FIDString { get; set; }
    
        public virtual Connection Connection { get; set; }
        public virtual ICollection<Node> Nodes { get; set; }
        public virtual DeviceType DeviceType { get; set; }
    }
}
