//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDeviceManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node
    {
        public Node()
        {
            this.Documents = new HashSet<Document>();
            this.Node1 = new HashSet<Node>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> FolderID { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual Folder Folder { get; set; }
        public virtual ICollection<Node> Node1 { get; set; }
        public virtual Node Node2 { get; set; }
    }
}
