//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 12/12/2013 6:25:23 AM
namespace WPFClientApp.DeviceServiceReference
{
    
    /// <summary>
    /// There are no comments for DeviceDatabaseEntities in the schema.
    /// </summary>
    public partial class DeviceDatabaseEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new DeviceDatabaseEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DeviceDatabaseEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("DeviceDatabaseModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("WPFClientApp.DeviceServiceReference", typeName.Substring(19)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WPFClientApp.DeviceServiceReference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("DeviceDatabaseModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Connections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Connection> Connections
        {
            get
            {
                if ((this._Connections == null))
                {
                    this._Connections = base.CreateQuery<Connection>("Connections");
                }
                return this._Connections;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Connection> _Connections;
        /// <summary>
        /// There are no comments for ConnectionTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ConnectionType> ConnectionTypes
        {
            get
            {
                if ((this._ConnectionTypes == null))
                {
                    this._ConnectionTypes = base.CreateQuery<ConnectionType>("ConnectionTypes");
                }
                return this._ConnectionTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ConnectionType> _ConnectionTypes;
        /// <summary>
        /// There are no comments for Devices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Device> Devices
        {
            get
            {
                if ((this._Devices == null))
                {
                    this._Devices = base.CreateQuery<Device>("Devices");
                }
                return this._Devices;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Device> _Devices;
        /// <summary>
        /// There are no comments for DeviceTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DeviceType> DeviceTypes
        {
            get
            {
                if ((this._DeviceTypes == null))
                {
                    this._DeviceTypes = base.CreateQuery<DeviceType>("DeviceTypes");
                }
                return this._DeviceTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DeviceType> _DeviceTypes;
        /// <summary>
        /// There are no comments for Documents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Document> Documents
        {
            get
            {
                if ((this._Documents == null))
                {
                    this._Documents = base.CreateQuery<Document>("Documents");
                }
                return this._Documents;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Document> _Documents;
        /// <summary>
        /// There are no comments for Folders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Folder> Folders
        {
            get
            {
                if ((this._Folders == null))
                {
                    this._Folders = base.CreateQuery<Folder>("Folders");
                }
                return this._Folders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Folder> _Folders;
        /// <summary>
        /// There are no comments for Nodes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Node> Nodes
        {
            get
            {
                if ((this._Nodes == null))
                {
                    this._Nodes = base.CreateQuery<Node>("Nodes");
                }
                return this._Nodes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Node> _Nodes;
        /// <summary>
        /// There are no comments for Connections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToConnections(Connection connection)
        {
            base.AddObject("Connections", connection);
        }
        /// <summary>
        /// There are no comments for ConnectionTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToConnectionTypes(ConnectionType connectionType)
        {
            base.AddObject("ConnectionTypes", connectionType);
        }
        /// <summary>
        /// There are no comments for Devices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDevices(Device device)
        {
            base.AddObject("Devices", device);
        }
        /// <summary>
        /// There are no comments for DeviceTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDeviceTypes(DeviceType deviceType)
        {
            base.AddObject("DeviceTypes", deviceType);
        }
        /// <summary>
        /// There are no comments for Documents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDocuments(Document document)
        {
            base.AddObject("Documents", document);
        }
        /// <summary>
        /// There are no comments for Folders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFolders(Folder folder)
        {
            base.AddObject("Folders", folder);
        }
        /// <summary>
        /// There are no comments for Nodes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNodes(Node node)
        {
            base.AddObject("Nodes", node);
        }
    }
    /// <summary>
    /// There are no comments for DeviceDatabaseModel.Connection in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Connections")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Connection : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Connection object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="connectionTypeID">Initial value of ConnectionTypeID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Connection CreateConnection(int ID, int connectionTypeID)
        {
            Connection connection = new Connection();
            connection.ID = ID;
            connection.ConnectionTypeID = connectionTypeID;
            return connection;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property ConnectionTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ConnectionTypeID
        {
            get
            {
                return this._ConnectionTypeID;
            }
            set
            {
                this.OnConnectionTypeIDChanging(value);
                this._ConnectionTypeID = value;
                this.OnConnectionTypeIDChanged();
                this.OnPropertyChanged("ConnectionTypeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ConnectionTypeID;
        partial void OnConnectionTypeIDChanging(int value);
        partial void OnConnectionTypeIDChanged();
        /// <summary>
        /// There are no comments for Property BaudRate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> BaudRate
        {
            get
            {
                return this._BaudRate;
            }
            set
            {
                this.OnBaudRateChanging(value);
                this._BaudRate = value;
                this.OnBaudRateChanged();
                this.OnPropertyChanged("BaudRate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _BaudRate;
        partial void OnBaudRateChanging(global::System.Nullable<int> value);
        partial void OnBaudRateChanged();
        /// <summary>
        /// There are no comments for Property DataBits in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> DataBits
        {
            get
            {
                return this._DataBits;
            }
            set
            {
                this.OnDataBitsChanging(value);
                this._DataBits = value;
                this.OnDataBitsChanged();
                this.OnPropertyChanged("DataBits");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _DataBits;
        partial void OnDataBitsChanging(global::System.Nullable<int> value);
        partial void OnDataBitsChanged();
        /// <summary>
        /// There are no comments for Property StopBits in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> StopBits
        {
            get
            {
                return this._StopBits;
            }
            set
            {
                this.OnStopBitsChanging(value);
                this._StopBits = value;
                this.OnStopBitsChanged();
                this.OnPropertyChanged("StopBits");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _StopBits;
        partial void OnStopBitsChanging(global::System.Nullable<int> value);
        partial void OnStopBitsChanged();
        /// <summary>
        /// There are no comments for Property RTSCTS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> RTSCTS
        {
            get
            {
                return this._RTSCTS;
            }
            set
            {
                this.OnRTSCTSChanging(value);
                this._RTSCTS = value;
                this.OnRTSCTSChanged();
                this.OnPropertyChanged("RTSCTS");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _RTSCTS;
        partial void OnRTSCTSChanging(global::System.Nullable<int> value);
        partial void OnRTSCTSChanged();
        /// <summary>
        /// There are no comments for Property DTR in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> DTR
        {
            get
            {
                return this._DTR;
            }
            set
            {
                this.OnDTRChanging(value);
                this._DTR = value;
                this.OnDTRChanged();
                this.OnPropertyChanged("DTR");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _DTR;
        partial void OnDTRChanging(global::System.Nullable<int> value);
        partial void OnDTRChanged();
        /// <summary>
        /// There are no comments for Property RTS in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> RTS
        {
            get
            {
                return this._RTS;
            }
            set
            {
                this.OnRTSChanging(value);
                this._RTS = value;
                this.OnRTSChanged();
                this.OnPropertyChanged("RTS");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _RTS;
        partial void OnRTSChanging(global::System.Nullable<int> value);
        partial void OnRTSChanged();
        /// <summary>
        /// There are no comments for Property XonXoff in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> XonXoff
        {
            get
            {
                return this._XonXoff;
            }
            set
            {
                this.OnXonXoffChanging(value);
                this._XonXoff = value;
                this.OnXonXoffChanged();
                this.OnPropertyChanged("XonXoff");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _XonXoff;
        partial void OnXonXoffChanging(global::System.Nullable<int> value);
        partial void OnXonXoffChanged();
        /// <summary>
        /// There are no comments for Devices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Device> Devices
        {
            get
            {
                return this._Devices;
            }
            set
            {
                this._Devices = value;
                this.OnPropertyChanged("Devices");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Device> _Devices = new global::System.Data.Services.Client.DataServiceCollection<Device>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for ConnectionType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ConnectionType ConnectionType
        {
            get
            {
                return this._ConnectionType;
            }
            set
            {
                this._ConnectionType = value;
                this.OnPropertyChanged("ConnectionType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ConnectionType _ConnectionType;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DeviceDatabaseModel.ConnectionType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ConnectionTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class ConnectionType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ConnectionType object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ConnectionType CreateConnectionType(int ID, string name)
        {
            ConnectionType connectionType = new ConnectionType();
            connectionType.ID = ID;
            connectionType.Name = name;
            return connectionType;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Connections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Connection> Connections
        {
            get
            {
                return this._Connections;
            }
            set
            {
                this._Connections = value;
                this.OnPropertyChanged("Connections");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Connection> _Connections = new global::System.Data.Services.Client.DataServiceCollection<Connection>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DeviceDatabaseModel.Device in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Devices")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Device : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Device object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="deviceTypeID">Initial value of DeviceTypeID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Device CreateDevice(int ID, int deviceTypeID)
        {
            Device device = new Device();
            device.ID = ID;
            device.DeviceTypeID = deviceTypeID;
            return device;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property DeviceTypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int DeviceTypeID
        {
            get
            {
                return this._DeviceTypeID;
            }
            set
            {
                this.OnDeviceTypeIDChanging(value);
                this._DeviceTypeID = value;
                this.OnDeviceTypeIDChanged();
                this.OnPropertyChanged("DeviceTypeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _DeviceTypeID;
        partial void OnDeviceTypeIDChanging(int value);
        partial void OnDeviceTypeIDChanged();
        /// <summary>
        /// There are no comments for Property ConnectionID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ConnectionID
        {
            get
            {
                return this._ConnectionID;
            }
            set
            {
                this.OnConnectionIDChanging(value);
                this._ConnectionID = value;
                this.OnConnectionIDChanged();
                this.OnPropertyChanged("ConnectionID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ConnectionID;
        partial void OnConnectionIDChanging(global::System.Nullable<int> value);
        partial void OnConnectionIDChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property SerialNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SerialNumber
        {
            get
            {
                return this._SerialNumber;
            }
            set
            {
                this.OnSerialNumberChanging(value);
                this._SerialNumber = value;
                this.OnSerialNumberChanged();
                this.OnPropertyChanged("SerialNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SerialNumber;
        partial void OnSerialNumberChanging(string value);
        partial void OnSerialNumberChanged();
        /// <summary>
        /// There are no comments for Property FirmwareRevision in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirmwareRevision
        {
            get
            {
                return this._FirmwareRevision;
            }
            set
            {
                this.OnFirmwareRevisionChanging(value);
                this._FirmwareRevision = value;
                this.OnFirmwareRevisionChanged();
                this.OnPropertyChanged("FirmwareRevision");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirmwareRevision;
        partial void OnFirmwareRevisionChanging(string value);
        partial void OnFirmwareRevisionChanged();
        /// <summary>
        /// There are no comments for Property PartNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PartNumber
        {
            get
            {
                return this._PartNumber;
            }
            set
            {
                this.OnPartNumberChanging(value);
                this._PartNumber = value;
                this.OnPartNumberChanged();
                this.OnPropertyChanged("PartNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PartNumber;
        partial void OnPartNumberChanging(string value);
        partial void OnPartNumberChanged();
        /// <summary>
        /// There are no comments for Property FIDString in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FIDString
        {
            get
            {
                return this._FIDString;
            }
            set
            {
                this.OnFIDStringChanging(value);
                this._FIDString = value;
                this.OnFIDStringChanged();
                this.OnPropertyChanged("FIDString");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FIDString;
        partial void OnFIDStringChanging(string value);
        partial void OnFIDStringChanged();
        /// <summary>
        /// There are no comments for Connection in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Connection Connection
        {
            get
            {
                return this._Connection;
            }
            set
            {
                this._Connection = value;
                this.OnPropertyChanged("Connection");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Connection _Connection;
        /// <summary>
        /// There are no comments for Nodes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Node> Nodes
        {
            get
            {
                return this._Nodes;
            }
            set
            {
                this._Nodes = value;
                this.OnPropertyChanged("Nodes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Node> _Nodes = new global::System.Data.Services.Client.DataServiceCollection<Node>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for DeviceType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DeviceType DeviceType
        {
            get
            {
                return this._DeviceType;
            }
            set
            {
                this._DeviceType = value;
                this.OnPropertyChanged("DeviceType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private DeviceType _DeviceType;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DeviceDatabaseModel.DeviceType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DeviceTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class DeviceType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DeviceType object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="canHaveChildren">Initial value of CanHaveChildren.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DeviceType CreateDeviceType(int ID, bool canHaveChildren)
        {
            DeviceType deviceType = new DeviceType();
            deviceType.ID = ID;
            deviceType.CanHaveChildren = canHaveChildren;
            return deviceType;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CanHaveChildren in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool CanHaveChildren
        {
            get
            {
                return this._CanHaveChildren;
            }
            set
            {
                this.OnCanHaveChildrenChanging(value);
                this._CanHaveChildren = value;
                this.OnCanHaveChildrenChanged();
                this.OnPropertyChanged("CanHaveChildren");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _CanHaveChildren;
        partial void OnCanHaveChildrenChanging(bool value);
        partial void OnCanHaveChildrenChanged();
        /// <summary>
        /// There are no comments for Devices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Device> Devices
        {
            get
            {
                return this._Devices;
            }
            set
            {
                this._Devices = value;
                this.OnPropertyChanged("Devices");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Device> _Devices = new global::System.Data.Services.Client.DataServiceCollection<Device>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DeviceDatabaseModel.Document in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Documents")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Document : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Document object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="data">Initial value of Data.</param>
        /// <param name="nodeID">Initial value of NodeID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Document CreateDocument(int ID, string name, byte[] data, int nodeID)
        {
            Document document = new Document();
            document.ID = ID;
            document.Name = name;
            document.Data = data;
            document.NodeID = nodeID;
            return document;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Data in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] Data
        {
            get
            {
                if ((this._Data != null))
                {
                    return ((byte[])(this._Data.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnDataChanging(value);
                this._Data = value;
                this.OnDataChanged();
                this.OnPropertyChanged("Data");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _Data;
        partial void OnDataChanging(byte[] value);
        partial void OnDataChanged();
        /// <summary>
        /// There are no comments for Property NodeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int NodeID
        {
            get
            {
                return this._NodeID;
            }
            set
            {
                this.OnNodeIDChanging(value);
                this._NodeID = value;
                this.OnNodeIDChanged();
                this.OnPropertyChanged("NodeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _NodeID;
        partial void OnNodeIDChanging(int value);
        partial void OnNodeIDChanged();
        /// <summary>
        /// There are no comments for Node in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Node Node
        {
            get
            {
                return this._Node;
            }
            set
            {
                this._Node = value;
                this.OnPropertyChanged("Node");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Node _Node;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DeviceDatabaseModel.Folder in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Folders")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Folder : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Folder object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Folder CreateFolder(int ID, string name)
        {
            Folder folder = new Folder();
            folder.ID = ID;
            folder.Name = name;
            return folder;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Nodes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Node> Nodes
        {
            get
            {
                return this._Nodes;
            }
            set
            {
                this._Nodes = value;
                this.OnPropertyChanged("Nodes");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Node> _Nodes = new global::System.Data.Services.Client.DataServiceCollection<Node>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DeviceDatabaseModel.Node in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Nodes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Node : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Node object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Node CreateNode(int ID)
        {
            Node node = new Node();
            node.ID = ID;
            return node;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property ParentID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ParentID
        {
            get
            {
                return this._ParentID;
            }
            set
            {
                this.OnParentIDChanging(value);
                this._ParentID = value;
                this.OnParentIDChanged();
                this.OnPropertyChanged("ParentID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ParentID;
        partial void OnParentIDChanging(global::System.Nullable<int> value);
        partial void OnParentIDChanged();
        /// <summary>
        /// There are no comments for Property DeviceID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> DeviceID
        {
            get
            {
                return this._DeviceID;
            }
            set
            {
                this.OnDeviceIDChanging(value);
                this._DeviceID = value;
                this.OnDeviceIDChanged();
                this.OnPropertyChanged("DeviceID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _DeviceID;
        partial void OnDeviceIDChanging(global::System.Nullable<int> value);
        partial void OnDeviceIDChanged();
        /// <summary>
        /// There are no comments for Property FolderID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> FolderID
        {
            get
            {
                return this._FolderID;
            }
            set
            {
                this.OnFolderIDChanging(value);
                this._FolderID = value;
                this.OnFolderIDChanged();
                this.OnPropertyChanged("FolderID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _FolderID;
        partial void OnFolderIDChanging(global::System.Nullable<int> value);
        partial void OnFolderIDChanged();
        /// <summary>
        /// There are no comments for Device in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Device Device
        {
            get
            {
                return this._Device;
            }
            set
            {
                this._Device = value;
                this.OnPropertyChanged("Device");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Device _Device;
        /// <summary>
        /// There are no comments for Documents in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Document> Documents
        {
            get
            {
                return this._Documents;
            }
            set
            {
                this._Documents = value;
                this.OnPropertyChanged("Documents");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Document> _Documents = new global::System.Data.Services.Client.DataServiceCollection<Document>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Folder in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Folder Folder
        {
            get
            {
                return this._Folder;
            }
            set
            {
                this._Folder = value;
                this.OnPropertyChanged("Folder");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Folder _Folder;
        /// <summary>
        /// There are no comments for Children in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Node> Children
        {
            get
            {
                return this._Children;
            }
            set
            {
                this._Children = value;
                this.OnPropertyChanged("Children");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Node> _Children = new global::System.Data.Services.Client.DataServiceCollection<Node>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Node2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Node Node2
        {
            get
            {
                return this._Node2;
            }
            set
            {
                this._Node2 = value;
                this.OnPropertyChanged("Node2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Node _Node2;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
